### ISSUE TITLE
Datasets won't appear after exiting with CTRL+C

### ISSUE THREAD

**Issue by SinRas** [ibcn-cloudlet/dianne#10]
I exited the __java -jar tools/generated/distributions/executable/all.jar__ process with `CTRL+C`.
Now the __Datasets__ don't appear in the UI menu (but exist in the folder).

I have tried deleting/redownloading the folders _models_ and _datasets_.

Build: `./gradlew build`

**Comment by tverbele** [comment]
The Java process should remain running the whole time. If you exit the Java process, the runtime is basically down, and all you see is some html/javascript cached by the browser...

**Comment by SinRas** [comment]
I miss informed the problem :sweat_smile: 

I shut down the java process with `CTRL+C` and now whenever I rerun __java -jar tools/generated/distributions/executable/all.jar__, the datasets won't appear.

Now neither of the following options work, when the Java process is working:
- Load (Models don't appear)
- Save (Can't find saves or load them after saving)
- Datasets do not appear

**Comment by tverbele** [comment]
Oh ok. Try running in the tools directory, so
```
cd tools
java -jar generated/distributions/executable/all.jar
```
By default the datasets and models are loaded from a `datasets` and `models` directory relative to where you start the process, which are by default located in the tools directory.

If you have stored models/datasets somewhere else, you can try to start with the following additional properties:
```
java -Dbe.iminds.iot.dianne.storage=<path to your models directory> -Dbe.iminds.iot.dianne.datasets.location=<path to your datasets directory> -jar generated/distributions/executable/all.jar
```

**Comment by SinRas** [comment]
many thanks
