### ISSUE TITLE
help！

### ISSUE THREAD

**Issue by zhuhuilong** [ibcn-cloudlet/dianne#12]
I got following error when I execute./gradlew run.all [Any of them; all , core etc.]

![image](https://user-images.githubusercontent.com/34827959/37135535-a08264c0-22d8-11e8-94f1-d342d79b7087.png)

**Comment by tverbele** [comment]
This is probably related to #11 since the build didn't work. You can also check the [Dianne examples repository](https://github.com/ibcn-cloudlet/dianne-examples) with some example runs that uses pre-built Dianne bundles, allowing you to skip the build process.
