### ISSUE TITLE
help with this error please

### ISSUE THREAD

**Issue by khalidpandit** [ibcn-cloudlet/dianne#13]
![d1](https://user-images.githubusercontent.com/13897759/37911851-c5323124-312e-11e8-947d-0f23207c9c39.png)
please help with this error

while running ./gradlew build command i am getting this error

**Comment by tverbele** [comment]
It is hard to see what went wrong from just this screenshot. You can also run Dianne using prebuilt binaries instead of building the complete source tree, e.g. check the examples repository: https://github.com/ibcn-cloudlet/dianne-examples

**Comment by eliasdc** [comment]
Based on your screenshot it fails with the following command:

```bash
cp /home/khalid/be.iminds.iot.dianne.rl.environment.ale/impl.bnd.template /home/khalid/be.iminds.iot.dianne.rl.environment.ale/impl.bnd
```

which overwrites the impl.bnd file if it exists and creates it otherwise. This should be possible on all Linux machines if you have write permissions on those folders. What you could try is to clean everything beforehand.

```bash
./gradlew cleanAll
```
