### ISSUE TITLE
Failing to run

### ISSUE THREAD

**Issue by EricLiu2000** [ibcn-cloudlet/dianne#15]
I'm on Mac High Sierra, and am currently having trouble running ./gradlew run.all and http://localhost:8080/dianne. The output of ./gradlew run.all is below:
<img width="1440" alt="output of gradlew run all" src="https://user-images.githubusercontent.com/8854674/42608256-d3c00732-853b-11e8-917b-e3d7c992dc6d.png">

Any help would be appreciated. Thanks.

**Comment by tverbele** [comment]
It seems it fails to load the native tensor library. Did `./gradlew build` succeed without errors?

**Comment by EricLiu2000** [comment]
Yes, finishes successfully.
<img width="1440" alt="screen shot 2018-07-11 at 11 04 11 pm" src="https://user-images.githubusercontent.com/8854674/42615360-bd5e0778-855e-11e8-8152-9664f58c3433.png">

I'm using the CPU version, if that's worth noting.

**Comment by tverbele** [comment]
Can you run `./gradlew cleanAll be.iminds.iot.dianne.tensor.native:build` to rebuild the native code and post the output?

**Comment by EricLiu2000** [comment]
<img width="1440" alt="screen shot 2018-07-11 at 11 11 59 pm" src="https://user-images.githubusercontent.com/8854674/42615615-d59e9ef0-855f-11e8-80f4-ae3c07917679.png">

**Comment by tverbele** [comment]
Clearly building the native code is failing.
Did you initialize the submodules? i.e. run
```
git submodule init
git submodule update
```

**Comment by EricLiu2000** [comment]
Just ran both commands with no result.
<img width="394" alt="screen shot 2018-07-12 at 12 27 42 am" src="https://user-images.githubusercontent.com/8854674/42618619-6f1fd0da-856a-11e8-99cf-ebd670e7bf69.png">

**Comment by tverbele** [comment]
It seems OpenBLAS is complaining that clang is not supporting OpenMP on your system. Maybe [this](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/) can help (I am not a Mac user myself unfortunately). Another option is to run inside a (ubuntu) docker container. If you have docker installed, you should be able to build a docker with DIANNE using the `./gradlew docker` command.

**Comment by EricLiu2000** [comment]
I've just installed the OpenMP runtime library. Which commands should I specifically call OpenMP on?

**Comment by tverbele** [comment]
Try to build again with `./gradlew cleanAll build` ?

**Comment by EricLiu2000** [comment]
It seems to encounter the same error, however this time around it took much longer.
<img width="1440" alt="screen shot 2018-07-12 at 1 20 57 am" src="https://user-images.githubusercontent.com/8854674/42621213-0b0676aa-8572-11e8-853f-37d0dc88333f.png">

**Comment by sbohez** [comment]
Hi Eric,

It seems your `gcc` compiler is a symlink to Apple's `clang`, which unfortunately does not support OpenMP. You can however install `gcc` via Homebrew:
```
brew install gcc --without-multilib
```
This might take a while, because `brew` has to compile `gcc` (compiling a compiler, the irony) due to the `--without-multilib`. Once finished, `gcc` will still point to `clang`, as not to break Apple's systems, but you can explicitly set the compiler using:
```
CC=gcc-8 CXX=g++-8 ./gradlew build
```
This is assuming you installed the latest version available from HomeBrew. I've not been able to test this one though, so if you run into trouble, I suggest you try `gcc-6` which is tested.

Please let us know if this works.

**Comment by EricLiu2000** [comment]
<img width="1440" alt="screen shot 2018-07-12 at 5 09 07 am" src="https://user-images.githubusercontent.com/8854674/42632570-721436aa-8592-11e8-8e1f-1b68a35da9a6.png">
<img width="1431" alt="screen shot 2018-07-12 at 5 14 00 am" src="https://user-images.githubusercontent.com/8854674/42632582-7c0092f8-8592-11e8-8c2d-b7fef0469bcd.png">
It works! Thank you for your help. I'd actually previously already tried these same commands (to no avail), and brew complains about the --without-multilib option not existing (which it still does, but irrelevant now). Seems like separately installing the OpenMP library fixed the issue! Thanks again.

**Comment by tverbele** [comment]
Great! Have fun!
