### ISSUE TITLE
Ant fails when building on ubuntu 14.04

### ISSUE THREAD

**Issue by nicojanssens** [ibcn-cloudlet/dianne#2]
`$ant clean build` generates the following error:

BUILD FAILED
/dianne/build.xml:25: The following error occurred while executing this line:
/dianne/build.xml:10: The following error occurred while executing this line:
/dianne/cnf/build-template.xml:53: The following error occurred while executing this line:
/dianne/cnf/build-template.xml:71: Error running javac compiler

**Comment by tverbele** [comment]
Which JDK version do you have installed?

**Comment by nicojanssens** [comment]
root@a2f30e9bc601:/dianne# java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

OK, just read in your prerequisites section that I need to use JDK 1.8.

**Comment by tverbele** [comment]
Indeed, you can install JDK 1.8 on ubuntu 14.04 using the following commands:

```
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer
```

**Comment by nicojanssens** [comment]
That did the trick, thx!
