### ISSUE TITLE
ant minst throws a service location exception

### ISSUE THREAD

**Issue by nicojanssens** [ibcn-cloudlet/dianne#3]
On OSX, executing `$ant minst` generates the following exception:

[java] [MGMT-0]12:23:45 ERROR - Exception in initial DA lookup
[java] [MGMT-0]ch.ethz.iks.slp.ServiceLocationException: No route to host

Not sure what route you're trying to establish.

**Comment by tverbele** [comment]
By default we have a SLP-based discovery bundle installed that tries to connect to remote DIANNE runtimes. From the error that is logged I would think that the SLP bundle found an SLP url advertisement but failed to connect to that device (since it is not a DIANNE runtime). This can be ignored.

**Comment by nicojanssens** [comment]
OK, thanks!

When I try to open `http://localhost:8080/dianne`, my browser complains about the page not being redirected properly (to `http://localhost:8080/dianne/ui/dianne.html`, I guess). Same symptom when using Chrome, Firefox and Safari (all browsers accept cookies).

Did you experience this or similar issues before?

**Comment by tverbele** [comment]
This is known issue with v0.3.0. We are currently working on release 0.4 (expected soon) where this should be resolved (next to a lot of other major changes and updates).

**Comment by nicojanssens** [comment]
OK, thanks for the update. Keep me posted when you release 0.4.
